import type { CareerProps } from "../types/career";

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer',
    company: 'Relfor Labs Pvt. Ltd.',
    logo: '/images/career/relfor.PNG',
    location: 'Pune, Maharashtra 🇮🇳',
    location_type: 'In-Person',
    type: 'Fulltime',
    start_date: '2024-04',
    end_date: null,
    industry: 'e-commerce and hospitality',
    link: 'https://www.relfor.com/',
    responsibilities: [
      'Architected an RFID-Based stored-value payment system, enabling low-latency tap-to-pay transactions through prepaid balances; handled multi-tenant usage across departments (e.g., food and liquor) with consistent balance management and real-time transaction processing at high-scale environments, handling 10K+ users daily.',
      'Led end-to-end development of a centralized inventory system (CKI) using Java, Spring Boot and React, improving production efficiency by ~50% and contributing to ~20% growth in new customers.',
      'Architected a robust inventory management workflow integrated with POS systems, handling complex item hierarchies (portions, add-ons) and implementing a time-bound stock reversion mechanism for order cancellations and modifications, ensuring data consistency and accurate inventory state management.',
      'Re-architected the role-based access control (RBAC) module, eliminating conflicting role assignments and fixing authorization flaws in login workflows, ensuring consistent permission handling across the system.',
      'Optimized high-traffic backend services, reducing API response times by ~40% through query optimization, API restructuring and code refactoring.',
    ],
  },
  {
    position: 'SWE Intern',
    company: 'Arthrex India Inc.',
    logo: '/images/career/athrex.PNG',
    location: 'Pune, Maharashtra 🇮🇳',
    location_type: 'Remote',
    type: 'Internship',
    start_date: '2024-02',
    end_date: '2024-03',
    industry: 'medical-ai',
    link: 'https://www.arthrex.com/',
    responsibilities: [
      'Conceptualized, designed, and developed a user-friendly dashboard utilizing microservices architecture with Python, Flask and ReactJS following Test-Driven Development (TDD) principles.',
      'Streamlined the process of displaying and disseminating data points in graph format, thereby minimizing manual effort and enhancing efficiency.',
    ],
  },
  {
    position: 'Business Analyst Intern',
    company: 'Loyalty Juggernaut Inc',
    logo: '/images/career/lji.PNG',
    location: 'Hyderabad, Telangana 🇮🇳',
    location_type: 'In-Person',
    type: 'Internship',
    start_date: '2023-01',
    end_date: '2023-05',
    industry: 'loyalty-tech',
    link: 'https://www.lji.io/',
    responsibilities: [
      'Conducted comprehensive market research and analysis to support strategic business decisions at Loyalty Juggernaut.',
      'Collaborated with cross-functional teams to gather requirements and develop solutions for business problems.',
      'Prepared and presented detailed reports to senior management, outlining key findings and actionable recommendations.',
      'Responsible for requirement gathering, analysis and research on top loyalty programs in the world. ',
      'Conducted market research, user testing, and competitive analysis that contributed to a 20% increase in costumer retention and customer acquisition metrics.',
      'Developed custom reports using SQL and Python tailored to customer requirements, driving a 30% improvement in efficiency and enabling faster, data-driven insights.'
    ],
  },
  {
    position: 'Design Engineer Intern',
    company: 'n-Gen Control Systems',
    logo: '/images/career/ngen.PNG',
    location: 'Pune, Maharashtra 🇮🇳',
    location_type: 'In-person',
    type: 'Internship',
    start_date: '2022-08',
    end_date: '2022-12',
    industry: 'product-manufacturing',
    link: 'https://www.ngen-group.com/',
    responsibilities: [
      'Worked in the Conveyor Design department on multiple engineering projects involving conveyor systems.',
      'Analyzed and studied key design parameters required for efficient conveyor systems performance.',
      'Assisted in designing conveyor systems based on project specificationsand operational requirements.',
      'Contributed to the modification and improvement of existing conveyor system designs.',
      'Collaborated with team members to support project execution, design optimization, and system functionality.',
    ],
  },
  {
    position: 'Machine Learning Engineer',
    company: 'The Robotics Forum (TRF)',
    logo: '/images/career/trf.PNG',
    location: 'Pune, Maharashtra 🇮🇳',
    location_type: 'Hybrid',
    type: 'Internship',
    start_date: '2020-08',
    end_date: '2022-08',
    industry: 'robotics-ai',
    link: 'https://www.vitpunerobotics.com/',
    responsibilities: [
      'Designed and developed Speech to Text Model using NLP Techniques.',
      'Designed a book recommendation system as a part of the training process.',
    ],
  },
  {
    position: 'SDE Summer Intern',
    company: 'The Robotics Forum (TRF)',
    logo: '/images/career/trf.PNG',
    location: 'Pune, India 🇮🇳',
    location_type: 'Remote',
    type: 'Internship',
    start_date: '2020-05',
    end_date: '2020-08',
    industry: 'software',
    link: 'https://www.vitpunerobotics.com/',
    responsibilities: [
      'Created an eCommerce platform for street grocery vendors using React.js and Firebase',
      'Engineered essential features including cart management, secure payment gateway, menus, and user profiles',
      'Utilized Firebase FireStore for database management and hosted the app on AWS',
    ],
  },
];