import { ProjectsProps } from "../types/projects";

export const PROJECTSLIST: ProjectsProps = {
  projects: [
    {
      title: 'Notification Management System',
      slug: 'notification-management-system',
      description:
        'A scalable multi-channel Notification Management System built using Java Spring Boot, React, Next.js, MySQL, and Tailwind CSS. The platform is designed to simulate modern enterprise notification infrastructure capable of handling real-time communication across multiple delivery channels including email, SMS, push, and in-app notifications.',
      image: 'https://github.com/Noddy09032001/Notification-Management-System',
      link_demo: 'https://github.com/Noddy09032001/Notification-Management-System',
      link_github: '#',
      stacks: [
        'Java',
        'Spring Boot',
        'MySQL',
        'System Design',
        'React.js',
        'Next.js',
        'Node.js',
        'TypeScript',
        'AuthJS'
      ],
      content: '',
      is_show: true,
      is_featured: true,
      updated_at: new Date(),
    },
    {
      title: 'ECommerce Platform',
      slug: 'ecommerce',
      description:
        'A full-stack e-commerce application built with modern technologies, focusing on secure authentication, payment processing, role-based access control, and real-world order management workflows.',
      image: '',
      link_demo: 'https://github.com/Noddy09032001/ECommerce-Practice',
      link_github: 'https://github.com/Noddy09032001/ECommerce-Practice',
      stacks: [
        'Java',
        'Spring Boot',
        'Next.js',
        'Node.js',
        'TypeScript',
        'MySQL',
        'React.js',
        'AuthJS'
      ],
      content: '',
      is_show: true,
      is_featured: true,
      updated_at: new Date(),
    },
    {
      title: 'VidQuery.AI - Query videos using statements and commands',
      slug: 'vidquery-ai',
      description:
        'Designed and implemented a Retrieval Augmented Generation (RAG) pipeline for semantic search and question answering over video transcripts using large language models (LLM’s)',
      image: '',
      link_demo: '#',
      link_github: '#',
      stacks: [
        'Next.js',
        'TypeScript',
        'MySQL',
        'Python',
        'TailwindCSS',
        'Machine Learning',
        'RAG',
        'LLM',
        'NLP',
        'Vector Database'
      ],
      content: '',
      is_show: true,
      is_featured: true,
      updated_at: new Date(),
    },
    {
      title: 'Resume Parser System',
      slug: 'resume-parser',
      description:
        'Developed an NLP-based resume parser that automatically extracts candidate information such as skills, education, experience, and contact details from resumes. Structured the extracted data for efficient search, filtering, and recruitment workflows.',
      image: '',
      link_demo: 'https://github.com/Noddy09032001/ML-AI-Projects',
      link_github: 'https://github.com/Noddy09032001/ML-AI-Projects',
      stacks: ['Python', 'Machine Learning', 'NLP', 'Data Analysis', 'HTML5', 'CSS'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Movie Recommendation System',
      slug: 'movie-recommendation-system',
      description:
        'Designed a movie recommendation system using collaborative and content-based filtering techniques to suggest personalized movies. Improved recommendation accuracy by analyzing user preferences, ratings, and movie metadata.',
      image: '',
      link_demo: 'https://github.com/Noddy09032001/ML-AI-Projects',
      link_github: 'https://github.com/Noddy09032001/ML-AI-Projects',
      stacks: ['Python', 'Machine Learning', 'NLP', 'Data Analysis', 'HTML5', 'CSS'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Vehicle Parking Management System',
      slug: 'parking-system',
      description:
        'Built a parking management system that handles real-time parking slot allocation, availability tracking, and vehicle entry/exit management. Automated parking operations to optimize slot utilization and reduce manual intervention.',
      image: '',
      link_demo: 'https://github.com/Noddy09032001/vehicle-parking-management-system',
      link_github: 'https://github.com/Noddy09032001/vehicle-parking-management-system',
      stacks: ['Java','Spring Boot','React.js', 'JavaScript', 'CSS', 'HTML5', 'MySQL'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
    {
      title: 'Spell Checker',
      slug: 'spell-checker',
      description:
        'Spell Checker Task - Built a custom spell checker system using Data Structures and Algorithms in C++. Used Hash tables and Trie Traversals for performance comparisons',
      image: '',
      link_demo: 'https://github.com/Noddy09032001/TRF_finaltask',
      link_github: 'https://github.com/Noddy09032001/TRF_finaltask',
      stacks: ['C++', 'Data Structures', 'Algorithms'],
      content: '',
      is_show: true,
      is_featured: false,
      updated_at: new Date(),
    },
  ],
};